--Vista para mostrar compras por cliente

CREATE OR REPLACE VIEW VISTA_COMPRAS_POR_CLIENTE AS
SELECT 
    C.CLAVE AS CLAVE_CLIENTE, 
    V.VENTA_ID AS VENTAID,
    C.NOMBRE AS CLIENTE, 
    C.MAIL, 
    V.FECHA AS FECHA_VENTA, 
    DV.TOTAL AS TOTAL_VENTA
FROM 
    CLIENTE C,
    VENTA V,
    DETALLE_VENTA DV
WHERE
 C.CLIENTE_ID = V.CLIENTE_ID AND
 V.VENTA_ID = DV.VENTA_ID
GROUP BY
    C.CLAVE, C.NOMBRE, C.MAIL, V.FECHA, V.VENTA_ID, DV.TOTAL;
    

-- Vista para mostrar el detalle de una venta
CREATE OR REPLACE VIEW VISTA_DETALLE_VENTA AS
SELECT 
    V.VENTA_ID, 
    P.DESCRIPCION AS PRODUCTO, 
    DV.CANTIDAD, 
    P.COSTO_UNITARIO, 
    DV.TOTAL
FROM 
    DETALLE_VENTA DV,
    PRODUCTO P ,
    VENTA V
WHERE 
    DV.PRODUCTO_ID = P.PRODUCTO_ID AND
    V.VENTA_ID = DV.VENTA_ID;

Select * from VISTA_DETALLE_VENTA where VENTA_ID=1


CREATE SEQUENCE SEQ_VENTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE;
